    <meta charset="utf-8" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="application/vnd.ms-excel;charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="./inc/styles.css">

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <!--script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script-->
    <script src="http://code.jquery.com/ui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>

    <script src="inc/script.js"></script>

    <script type="text/javascript">
        $(document).ready(function()
        {
            $('#menu_home').removeClass();
            $('#menu1').removeClass();
            $('#menu2').removeClass();
            $('#menu3').removeClass();

            active_css();
        });
    </script>
